/* Generated by Yosys 0.33 (git sha1 2584903a060) */
// Yosys Still reads as a mux
module async_en(data_in, clk, resetn, write_en, data_out);
  input clk;
  wire clk;
  input [15:0] data_in;
  wire [15:0] data_in;
  output [15:0] data_out;
  reg [15:0] data_out;
  input resetn;
  wire resetn;
  input write_en;
  wire write_en;
  always @(posedge clk, negedge resetn)
    if (!resetn) data_out <= 16'h0000;
    else if (write_en) data_out <= data_in;
endmodule
