/* Generated by Yosys 0.33 (git sha1 2584903a060) */
// Yosys Still reads as a mux
module sync_en(data_in, clk, resetn, write_en, data_out);
  input clk;
  wire clk;
  input data_in;
  wire data_in;
  output data_out;
  reg data_out;
  input resetn;
  wire resetn;
  input write_en;
  wire write_en;
  always @(posedge clk)
    if (!resetn) data_out <= 1'b0;
    else if (write_en) data_out <= data_in;
endmodule
