/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module sync_mux(data_in, clk, resetn, write_en, data_out);
  wire [15:0] _0_;
  wire [15:0] _1_;
  input clk;
  wire clk;
  input [15:0] data_in;
  wire [15:0] data_in;
  output [15:0] data_out;
  reg [15:0] data_out;
  input resetn;
  wire resetn;
  input write_en;
  wire write_en;
  always @(posedge clk)
    data_out <= _0_;
  assign _1_ = write_en ? data_in : data_out;
  assign _0_ = resetn ? _1_ : 16'h0000;
endmodule
