[package]
name = "svql_query_downstream"
version = "0.1.0"
edition = "2024"

[dependencies]
svql_common.workspace = true
svql_driver_handler.workspace = true
svql_query.workspace = true
itertools.workspace = true
regex.workspace = true
lazy_static.workspace = true
openport.workspace = true