// Generated by CIRCT firtool-1.87.0
module AddrDecode(
  input         clock,
                reset,
  input  [31:0] io_addrRaw,
  input         io_en,
                io_selInput,
  output        io_sel_0,
                io_sel_1,
                io_sel_2,
                io_sel_3,
                io_sel_4,
                io_sel_5,
                io_sel_6,
                io_sel_7,
                io_sel_8,
                io_sel_9,
                io_sel_10,
                io_sel_11,
                io_sel_12,
                io_sel_13,
                io_sel_14,
                io_sel_15,
                io_sel_16,
                io_sel_17,
                io_sel_18,
                io_sel_19,
                io_sel_20,
                io_sel_21,
                io_sel_22,
                io_sel_23,
                io_sel_24,
                io_sel_25,
                io_sel_26,
                io_sel_27,
                io_sel_28,
                io_sel_29,
                io_sel_30,
                io_sel_31,
  output [31:0] io_addrOut,
  output        io_errorCode,
  output [31:0] io_errorAddr
);

  wire [31:0] addrMasked = {22'h0, io_addrRaw[11:2]};
  wire        _GEN = io_en & io_selInput;
  wire        selOut_0 = addrMasked < 32'h20;
  wire        _io_addrOut_T_4 = addrMasked < 32'h40;
  wire        _io_addrOut_T_7 = addrMasked < 32'h60;
  wire        _io_addrOut_T_9 = addrMasked > 32'h5F;
  wire        _io_addrOut_T_10 = addrMasked < 32'h80;
  wire        _io_addrOut_T_13 = addrMasked < 32'hA0;
  wire        _io_addrOut_T_15 = addrMasked > 32'h9F;
  wire        _io_addrOut_T_16 = addrMasked < 32'hC0;
  wire        _io_addrOut_T_18 = addrMasked > 32'hBF;
  wire        _io_addrOut_T_19 = addrMasked < 32'hE0;
  wire        _io_addrOut_T_21 = addrMasked > 32'hDF;
  wire        _io_addrOut_T_22 = addrMasked < 32'h100;
  wire        _io_addrOut_T_25 = addrMasked < 32'h120;
  wire        _io_addrOut_T_27 = addrMasked > 32'h11F;
  wire        _io_addrOut_T_28 = addrMasked < 32'h140;
  wire        _io_addrOut_T_30 = addrMasked > 32'h13F;
  wire        _io_addrOut_T_31 = addrMasked < 32'h160;
  wire        _io_addrOut_T_33 = addrMasked > 32'h15F;
  wire        _io_addrOut_T_34 = addrMasked < 32'h180;
  wire        _io_addrOut_T_36 = addrMasked > 32'h17F;
  wire        _io_addrOut_T_37 = addrMasked < 32'h1A0;
  wire        _io_addrOut_T_39 = addrMasked > 32'h19F;
  wire        _io_addrOut_T_40 = addrMasked < 32'h1C0;
  wire        _io_addrOut_T_42 = addrMasked > 32'h1BF;
  wire        _io_addrOut_T_43 = addrMasked < 32'h1E0;
  wire        _io_addrOut_T_45 = addrMasked > 32'h1DF;
  wire        _io_addrOut_T_46 = addrMasked < 32'h200;
  wire        _io_addrOut_T_49 = addrMasked < 32'h220;
  wire        _io_addrOut_T_51 = addrMasked > 32'h21F;
  wire        _io_addrOut_T_52 = addrMasked < 32'h240;
  wire        _io_addrOut_T_54 = addrMasked > 32'h23F;
  wire        _io_addrOut_T_55 = addrMasked < 32'h260;
  wire        _io_addrOut_T_57 = addrMasked > 32'h25F;
  wire        _io_addrOut_T_58 = addrMasked < 32'h280;
  wire        _io_addrOut_T_60 = addrMasked > 32'h27F;
  wire        _io_addrOut_T_61 = addrMasked < 32'h2A0;
  wire        _io_addrOut_T_63 = addrMasked > 32'h29F;
  wire        _io_addrOut_T_64 = addrMasked < 32'h2C0;
  wire        _io_addrOut_T_66 = addrMasked > 32'h2BF;
  wire        _io_addrOut_T_67 = addrMasked < 32'h2E0;
  wire        _io_addrOut_T_69 = addrMasked > 32'h2DF;
  wire        _io_addrOut_T_70 = addrMasked < 32'h300;
  wire        _io_addrOut_T_72 = addrMasked > 32'h2FF;
  wire        _io_addrOut_T_73 = addrMasked < 32'h320;
  wire        _io_addrOut_T_75 = addrMasked > 32'h31F;
  wire        _io_addrOut_T_76 = addrMasked < 32'h340;
  wire        _io_addrOut_T_78 = addrMasked > 32'h33F;
  wire        _io_addrOut_T_79 = addrMasked < 32'h360;
  wire        _io_addrOut_T_81 = addrMasked > 32'h35F;
  wire        _io_addrOut_T_82 = addrMasked < 32'h380;
  wire        _io_addrOut_T_84 = addrMasked > 32'h37F;
  wire        _io_addrOut_T_85 = addrMasked < 32'h3A0;
  wire        _io_addrOut_T_87 = addrMasked > 32'h39F;
  wire        _io_addrOut_T_88 = addrMasked < 32'h3C0;
  wire        _io_addrOut_T_90 = addrMasked > 32'h3BF;
  wire        _io_addrOut_T_91 = addrMasked < 32'h3E0;
  wire        _io_addrOut_T_93 = addrMasked > 32'h3DF;
  wire        _io_addrOut_T_94 = addrMasked < 32'h400;
  wire [31:0] _GEN_0 = {22'h0, io_addrRaw[11:2]};
  assign io_sel_0 = _GEN & selOut_0;
  assign io_sel_1 = _GEN & (|(io_addrRaw[11:7])) & _io_addrOut_T_4;
  assign io_sel_2 = _GEN & (|(io_addrRaw[11:8])) & _io_addrOut_T_7;
  assign io_sel_3 = _GEN & _io_addrOut_T_9 & _io_addrOut_T_10;
  assign io_sel_4 = _GEN & (|(io_addrRaw[11:9])) & _io_addrOut_T_13;
  assign io_sel_5 = _GEN & _io_addrOut_T_15 & _io_addrOut_T_16;
  assign io_sel_6 = _GEN & _io_addrOut_T_18 & _io_addrOut_T_19;
  assign io_sel_7 = _GEN & _io_addrOut_T_21 & _io_addrOut_T_22;
  assign io_sel_8 = _GEN & (|(io_addrRaw[11:10])) & _io_addrOut_T_25;
  assign io_sel_9 = _GEN & _io_addrOut_T_27 & _io_addrOut_T_28;
  assign io_sel_10 = _GEN & _io_addrOut_T_30 & _io_addrOut_T_31;
  assign io_sel_11 = _GEN & _io_addrOut_T_33 & _io_addrOut_T_34;
  assign io_sel_12 = _GEN & _io_addrOut_T_36 & _io_addrOut_T_37;
  assign io_sel_13 = _GEN & _io_addrOut_T_39 & _io_addrOut_T_40;
  assign io_sel_14 = _GEN & _io_addrOut_T_42 & _io_addrOut_T_43;
  assign io_sel_15 = _GEN & _io_addrOut_T_45 & _io_addrOut_T_46;
  assign io_sel_16 = _GEN & io_addrRaw[11] & _io_addrOut_T_49;
  assign io_sel_17 = _GEN & _io_addrOut_T_51 & _io_addrOut_T_52;
  assign io_sel_18 = _GEN & _io_addrOut_T_54 & _io_addrOut_T_55;
  assign io_sel_19 = _GEN & _io_addrOut_T_57 & _io_addrOut_T_58;
  assign io_sel_20 = _GEN & _io_addrOut_T_60 & _io_addrOut_T_61;
  assign io_sel_21 = _GEN & _io_addrOut_T_63 & _io_addrOut_T_64;
  assign io_sel_22 = _GEN & _io_addrOut_T_66 & _io_addrOut_T_67;
  assign io_sel_23 = _GEN & _io_addrOut_T_69 & _io_addrOut_T_70;
  assign io_sel_24 = _GEN & _io_addrOut_T_72 & _io_addrOut_T_73;
  assign io_sel_25 = _GEN & _io_addrOut_T_75 & _io_addrOut_T_76;
  assign io_sel_26 = _GEN & _io_addrOut_T_78 & _io_addrOut_T_79;
  assign io_sel_27 = _GEN & _io_addrOut_T_81 & _io_addrOut_T_82;
  assign io_sel_28 = _GEN & _io_addrOut_T_84 & _io_addrOut_T_85;
  assign io_sel_29 = _GEN & _io_addrOut_T_87 & _io_addrOut_T_88;
  assign io_sel_30 = _GEN & _io_addrOut_T_90 & _io_addrOut_T_91;
  assign io_sel_31 = _GEN & _io_addrOut_T_93 & _io_addrOut_T_94;
  assign io_addrOut =
    _GEN
      ? (_io_addrOut_T_93 & _io_addrOut_T_94
           ? _GEN_0 - 32'h3E0
           : _io_addrOut_T_90 & _io_addrOut_T_91
               ? _GEN_0 - 32'h3C0
               : _io_addrOut_T_87 & _io_addrOut_T_88
                   ? _GEN_0 - 32'h3A0
                   : _io_addrOut_T_84 & _io_addrOut_T_85
                       ? _GEN_0 - 32'h380
                       : _io_addrOut_T_81 & _io_addrOut_T_82
                           ? _GEN_0 - 32'h360
                           : _io_addrOut_T_78 & _io_addrOut_T_79
                               ? _GEN_0 - 32'h340
                               : _io_addrOut_T_75 & _io_addrOut_T_76
                                   ? _GEN_0 - 32'h320
                                   : _io_addrOut_T_72 & _io_addrOut_T_73
                                       ? _GEN_0 - 32'h300
                                       : _io_addrOut_T_69 & _io_addrOut_T_70
                                           ? _GEN_0 - 32'h2E0
                                           : _io_addrOut_T_66 & _io_addrOut_T_67
                                               ? _GEN_0 - 32'h2C0
                                               : _io_addrOut_T_63 & _io_addrOut_T_64
                                                   ? _GEN_0 - 32'h2A0
                                                   : _io_addrOut_T_60 & _io_addrOut_T_61
                                                       ? _GEN_0 - 32'h280
                                                       : _io_addrOut_T_57
                                                         & _io_addrOut_T_58
                                                           ? _GEN_0 - 32'h260
                                                           : _io_addrOut_T_54
                                                             & _io_addrOut_T_55
                                                               ? _GEN_0 - 32'h240
                                                               : _io_addrOut_T_51
                                                                 & _io_addrOut_T_52
                                                                   ? _GEN_0 - 32'h220
                                                                   : io_addrRaw[11]
                                                                     & _io_addrOut_T_49
                                                                       ? _GEN_0 - 32'h200
                                                                       : _io_addrOut_T_45
                                                                         & _io_addrOut_T_46
                                                                           ? _GEN_0
                                                                             - 32'h1E0
                                                                           : _io_addrOut_T_42
                                                                             & _io_addrOut_T_43
                                                                               ? _GEN_0
                                                                                 - 32'h1C0
                                                                               : _io_addrOut_T_39
                                                                                 & _io_addrOut_T_40
                                                                                   ? _GEN_0
                                                                                     - 32'h1A0
                                                                                   : _io_addrOut_T_36
                                                                                     & _io_addrOut_T_37
                                                                                       ? _GEN_0
                                                                                         - 32'h180
                                                                                       : _io_addrOut_T_33
                                                                                         & _io_addrOut_T_34
                                                                                           ? _GEN_0
                                                                                             - 32'h160
                                                                                           : _io_addrOut_T_30
                                                                                             & _io_addrOut_T_31
                                                                                               ? _GEN_0
                                                                                                 - 32'h140
                                                                                               : _io_addrOut_T_27
                                                                                                 & _io_addrOut_T_28
                                                                                                   ? _GEN_0
                                                                                                     - 32'h120
                                                                                                   : (|(io_addrRaw[11:10]))
                                                                                                     & _io_addrOut_T_25
                                                                                                       ? _GEN_0
                                                                                                         - 32'h100
                                                                                                       : _io_addrOut_T_21
                                                                                                         & _io_addrOut_T_22
                                                                                                           ? _GEN_0
                                                                                                             - 32'hE0
                                                                                                           : _io_addrOut_T_18
                                                                                                             & _io_addrOut_T_19
                                                                                                               ? _GEN_0
                                                                                                                 - 32'hC0
                                                                                                               : _io_addrOut_T_15
                                                                                                                 & _io_addrOut_T_16
                                                                                                                   ? _GEN_0
                                                                                                                     - 32'hA0
                                                                                                                   : (|(io_addrRaw[11:9]))
                                                                                                                     & _io_addrOut_T_13
                                                                                                                       ? _GEN_0
                                                                                                                         - 32'h80
                                                                                                                       : _io_addrOut_T_9
                                                                                                                         & _io_addrOut_T_10
                                                                                                                           ? _GEN_0
                                                                                                                             - 32'h60
                                                                                                                           : (|(io_addrRaw[11:8]))
                                                                                                                             & _io_addrOut_T_7
                                                                                                                               ? _GEN_0
                                                                                                                                 - 32'h40
                                                                                                                               : (|(io_addrRaw[11:7]))
                                                                                                                                 & _io_addrOut_T_4
                                                                                                                                   ? _GEN_0
                                                                                                                                     - 32'h20
                                                                                                                                   : selOut_0
                                                                                                                                       ? addrMasked
                                                                                                                                       : 32'h0)
      : 32'h0;
  assign io_errorCode = 1'h0;
  assign io_errorAddr = 32'h0;
endmodule

