// Generated by CIRCT firtool-1.87.0
module AddrDecode(
  input         clock,
                reset,
  input  [15:0] io_addrRaw,
  input         io_en,
                io_selInput,
  output        io_sel_0,
                io_sel_1,
                io_sel_2,
                io_sel_3,
                io_sel_4,
                io_sel_5,
                io_sel_6,
                io_sel_7,
                io_sel_8,
                io_sel_9,
                io_sel_10,
                io_sel_11,
                io_sel_12,
                io_sel_13,
                io_sel_14,
                io_sel_15,
  output [15:0] io_addrOut,
  output        io_errorCode,
  output [15:0] io_errorAddr
);

  wire [15:0] addrMasked = {8'h0, io_addrRaw[8:1]};
  wire        _GEN = io_en & io_selInput;
  wire        selOut_0 = addrMasked < 16'h10;
  wire        _io_addrOut_T_4 = addrMasked < 16'h20;
  wire        _io_addrOut_T_7 = addrMasked < 16'h30;
  wire        _io_addrOut_T_9 = addrMasked > 16'h2F;
  wire        _io_addrOut_T_10 = addrMasked < 16'h40;
  wire        _io_addrOut_T_13 = addrMasked < 16'h50;
  wire        _io_addrOut_T_15 = addrMasked > 16'h4F;
  wire        _io_addrOut_T_16 = addrMasked < 16'h60;
  wire        _io_addrOut_T_18 = addrMasked > 16'h5F;
  wire        _io_addrOut_T_19 = addrMasked < 16'h70;
  wire        _io_addrOut_T_21 = addrMasked > 16'h6F;
  wire        _io_addrOut_T_22 = addrMasked < 16'h80;
  wire        _io_addrOut_T_25 = addrMasked < 16'h90;
  wire        _io_addrOut_T_27 = addrMasked > 16'h8F;
  wire        _io_addrOut_T_28 = addrMasked < 16'hA0;
  wire        _io_addrOut_T_30 = addrMasked > 16'h9F;
  wire        _io_addrOut_T_31 = addrMasked < 16'hB0;
  wire        _io_addrOut_T_33 = addrMasked > 16'hAF;
  wire        _io_addrOut_T_34 = addrMasked < 16'hC0;
  wire        _io_addrOut_T_36 = addrMasked > 16'hBF;
  wire        _io_addrOut_T_37 = addrMasked < 16'hD0;
  wire        _io_addrOut_T_39 = addrMasked > 16'hCF;
  wire        _io_addrOut_T_40 = addrMasked < 16'hE0;
  wire        _io_addrOut_T_42 = addrMasked > 16'hDF;
  wire        _io_addrOut_T_43 = addrMasked < 16'hF0;
  wire        _io_addrOut_T_45 = addrMasked > 16'hEF;
  wire        _io_addrOut_T_46 = addrMasked < 16'h100;
  wire [15:0] _GEN_0 = {8'h0, io_addrRaw[8:1]};
  assign io_sel_0 = _GEN & selOut_0;
  assign io_sel_1 = _GEN & (|(io_addrRaw[8:5])) & _io_addrOut_T_4;
  assign io_sel_2 = _GEN & (|(io_addrRaw[8:6])) & _io_addrOut_T_7;
  assign io_sel_3 = _GEN & _io_addrOut_T_9 & _io_addrOut_T_10;
  assign io_sel_4 = _GEN & (|(io_addrRaw[8:7])) & _io_addrOut_T_13;
  assign io_sel_5 = _GEN & _io_addrOut_T_15 & _io_addrOut_T_16;
  assign io_sel_6 = _GEN & _io_addrOut_T_18 & _io_addrOut_T_19;
  assign io_sel_7 = _GEN & _io_addrOut_T_21 & _io_addrOut_T_22;
  assign io_sel_8 = _GEN & io_addrRaw[8] & _io_addrOut_T_25;
  assign io_sel_9 = _GEN & _io_addrOut_T_27 & _io_addrOut_T_28;
  assign io_sel_10 = _GEN & _io_addrOut_T_30 & _io_addrOut_T_31;
  assign io_sel_11 = _GEN & _io_addrOut_T_33 & _io_addrOut_T_34;
  assign io_sel_12 = _GEN & _io_addrOut_T_36 & _io_addrOut_T_37;
  assign io_sel_13 = _GEN & _io_addrOut_T_39 & _io_addrOut_T_40;
  assign io_sel_14 = _GEN & _io_addrOut_T_42 & _io_addrOut_T_43;
  assign io_sel_15 = _GEN & _io_addrOut_T_45 & _io_addrOut_T_46;
  assign io_addrOut =
    _GEN
      ? (_io_addrOut_T_45 & _io_addrOut_T_46
           ? _GEN_0 - 16'hF0
           : _io_addrOut_T_42 & _io_addrOut_T_43
               ? _GEN_0 - 16'hE0
               : _io_addrOut_T_39 & _io_addrOut_T_40
                   ? _GEN_0 - 16'hD0
                   : _io_addrOut_T_36 & _io_addrOut_T_37
                       ? _GEN_0 - 16'hC0
                       : _io_addrOut_T_33 & _io_addrOut_T_34
                           ? _GEN_0 - 16'hB0
                           : _io_addrOut_T_30 & _io_addrOut_T_31
                               ? _GEN_0 - 16'hA0
                               : _io_addrOut_T_27 & _io_addrOut_T_28
                                   ? _GEN_0 - 16'h90
                                   : io_addrRaw[8] & _io_addrOut_T_25
                                       ? _GEN_0 - 16'h80
                                       : _io_addrOut_T_21 & _io_addrOut_T_22
                                           ? _GEN_0 - 16'h70
                                           : _io_addrOut_T_18 & _io_addrOut_T_19
                                               ? _GEN_0 - 16'h60
                                               : _io_addrOut_T_15 & _io_addrOut_T_16
                                                   ? _GEN_0 - 16'h50
                                                   : (|(io_addrRaw[8:7]))
                                                     & _io_addrOut_T_13
                                                       ? _GEN_0 - 16'h40
                                                       : _io_addrOut_T_9
                                                         & _io_addrOut_T_10
                                                           ? _GEN_0 - 16'h30
                                                           : (|(io_addrRaw[8:6]))
                                                             & _io_addrOut_T_7
                                                               ? _GEN_0 - 16'h20
                                                               : (|(io_addrRaw[8:5]))
                                                                 & _io_addrOut_T_4
                                                                   ? _GEN_0 - 16'h10
                                                                   : selOut_0
                                                                       ? addrMasked
                                                                       : 16'h0)
      : 16'h0;
  assign io_errorCode = 1'h0;
  assign io_errorAddr = 16'h0;
endmodule

