// Generated by CIRCT firtool-1.87.0
module AddrDecode(
  input        clock,
               reset,
  input  [7:0] io_addrRaw,
  input        io_en,
               io_selInput,
  output       io_sel_0,
               io_sel_1,
               io_sel_2,
               io_sel_3,
               io_sel_4,
               io_sel_5,
               io_sel_6,
               io_sel_7,
  output [7:0] io_addrOut,
  output       io_errorCode,
  output [7:0] io_errorAddr
);

  wire [7:0] addrMasked = {2'h0, io_addrRaw[5:0]};
  wire       _GEN = io_en & io_selInput;
  wire       selOut_0 = addrMasked < 8'h8;
  wire       _io_addrOut_T_4 = addrMasked < 8'h10;
  wire       _io_addrOut_T_7 = addrMasked < 8'h18;
  wire       _io_addrOut_T_9 = addrMasked > 8'h17;
  wire       _io_addrOut_T_10 = addrMasked < 8'h20;
  wire       _io_addrOut_T_13 = addrMasked < 8'h28;
  wire       _io_addrOut_T_15 = addrMasked > 8'h27;
  wire       _io_addrOut_T_16 = addrMasked < 8'h30;
  wire       _io_addrOut_T_18 = addrMasked > 8'h2F;
  wire       _io_addrOut_T_19 = addrMasked < 8'h38;
  wire       _io_addrOut_T_21 = addrMasked > 8'h37;
  wire       _io_addrOut_T_22 = addrMasked < 8'h40;
  wire [7:0] _GEN_0 = {2'h0, io_addrRaw[5:0]};
  assign io_sel_0 = _GEN & selOut_0;
  assign io_sel_1 = _GEN & (|(io_addrRaw[5:3])) & _io_addrOut_T_4;
  assign io_sel_2 = _GEN & (|(io_addrRaw[5:4])) & _io_addrOut_T_7;
  assign io_sel_3 = _GEN & _io_addrOut_T_9 & _io_addrOut_T_10;
  assign io_sel_4 = _GEN & io_addrRaw[5] & _io_addrOut_T_13;
  assign io_sel_5 = _GEN & _io_addrOut_T_15 & _io_addrOut_T_16;
  assign io_sel_6 = _GEN & _io_addrOut_T_18 & _io_addrOut_T_19;
  assign io_sel_7 = _GEN & _io_addrOut_T_21 & _io_addrOut_T_22;
  assign io_addrOut =
    _GEN
      ? (_io_addrOut_T_21 & _io_addrOut_T_22
           ? _GEN_0 - 8'h38
           : _io_addrOut_T_18 & _io_addrOut_T_19
               ? _GEN_0 - 8'h30
               : _io_addrOut_T_15 & _io_addrOut_T_16
                   ? _GEN_0 - 8'h28
                   : io_addrRaw[5] & _io_addrOut_T_13
                       ? _GEN_0 - 8'h20
                       : _io_addrOut_T_9 & _io_addrOut_T_10
                           ? _GEN_0 - 8'h18
                           : (|(io_addrRaw[5:4])) & _io_addrOut_T_7
                               ? _GEN_0 - 8'h10
                               : (|(io_addrRaw[5:3])) & _io_addrOut_T_4
                                   ? _GEN_0 - 8'h8
                                   : selOut_0 ? addrMasked : 8'h0)
      : 8'h0;
  assign io_errorCode = 1'h0;
  assign io_errorAddr = 8'h0;
endmodule

